git:
    depth: 5

stages:
    - "Build and Test"
    - "Package"

jobs:
    include:
        - stage: "Build and Test"
          language: java
          jdk: oraclejdk11
          before_script:
            - cd sample-application-backend
          script:
            - echo "Maven build"
            - mvn clean verify
            - echo "Run test coverage and Quality Gate"
            - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=nbiotte_sample-application-students
        - stage: "Build and Test"
          language: node.js
          node_js: "12.20"
          before_script:
            - cd sample-application-frontend
          script:
            - echo "NPM install and build"
            - npm run test
            
        - stage: "Package"
          before_script:
            - cd sample-application-backend
          script:
            - echo "Docker build ..."
            - docker build -t $DOCKER_USERNAME/tp02backend .
            - docker images
            - echo "Docker login ..."
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - echo "Docker push ..."
            - docker push $DOCKER_USERNAME/tp02backend
        - stage: "Package"
          before_script:
            - cd sample-application-frontend
          script:
            - echo "Docker build ..."
            - docker build -t $DOCKER_USERNAME/tp02frontend .
            - docker images
            - echo "Docker login ..."
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - echo "Docker push ..."
            - docker push $DOCKER_USERNAME/tp02frontend
cache:
    directories:
        - "$HOME/.m2/repository"
        - "$HOME/.npm"
        
services:
    - docker
    
addons:
    sonarcloud:
        organization: "nbiotte"
        token: "$SONARCLOUD_TOKEN"